version: '3.4'

services:
  be:
    image: ${DOCKER_REGISTRY-}be
    build:
      context: .
      dockerfile: BE/Dockerfile
    ports:
      - "8000:80"
    networks:
      - webnet
  bff:
    image: ${DOCKER_REGISTRY-}bff
    build:
      context: .
      dockerfile: BFF/Dockerfile
    ports:
      - "8001:80"
    networks:
      - webnet
  pis:
    image: ${DOCKER_REGISTRY-}pis
    build:
      context: .
      dockerfile: PulseIntegrationService/Dockerfile
    ports:
      - "8002:80"
    networks:
      - webnet
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: test
        RABBITMQ_DEFAULT_PASS: test
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - webnet

networks:
  webnet:
    external: true